image:
  repo: fudanzz/redis-shake
  tag: v1
  pullPolicy: IfNotPresent

## config files override
livenessProbe:
  path: /metric
  port: 9320
  initialDelaySeconds: 90
  periodSeconds: 30


conf: 
  conf.version: 1
  id: redis-shake
  log.file: redis-shake.log
  log.level: info
  pid_path:
  system_profile: 9310
  http_profile: 9320
  parallel: 32
  source.type: standalone
  source.address: 10.1.0.7:6379
  source.password_raw:
  source.auth_type: auth
  source.tls_enable: false
  source.rdb.input:
  source.rdb.parallel: 0
  source.rdb.special_cloud:
  target.type: standalone
  target.address: 10.1.0.8:6379
  target.password_raw:
  target.auth_type: auth
  target.db: -1
  target.dbmap:
  target.tls_enable: false
  target.rdb.output: local_dump
  target.version:
  fake_time:
  key_exists: rewrite
  filter.db.whitelist:
  filter.db.blacklist:
  filter.key.whitelist:
  filter.key.blacklist:
  filter.slot:
  filter.lua: false
  big_key_threshold: "524288000"
  metric: true
  metric.print_log: false
  sender.size: "104857600"
  sender.count: 4095
  sender.delay_channel_size: 65535
  keep_alive: 0
  scan.key_number: 50
  scan.special_cloud:
  scan.key_file:
  qps: "200000"
  resume_from_break_point: true
  replace_hash_tag: false
